Task/pet 2120
mcruncher/mcruncher.github.io pull request #30
Opened 2024-05-17 03:23 UTC by geraldjebanesan

Made total change of the Furiend+ Benefits page.

2024-05-17 07:24 UTC, VigneshPalanisamy requested changes

2024-05-21 00:25 UTC, VigneshPalanisamy commented on furiend/furiend-plus-features/index.html
> +      }
Move this to style.css

2024-05-21 02:10 UTC, geraldjebanesan commented on furiend/furiend-plus-features/index.html
> +      }
Done Vicky

2024-05-23 03:09 UTC, melissadarsh approved these changes

2024-05-23 03:11 UTC, melissadarsh approved these changes

2024-05-23 03:29 UTC, VigneshPalanisamy approved these changes

2024-05-23 03:31 UTC, merged